### ISSUE TITLE
Wrong use of parameter, reveals dead code

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-ugh#52]
The class `DocStruct` provides the three methods
* `removeMetadata(Metadata, boolean)`
* `removePerson(Person, boolean)`
* `removeMetadataGroup(MetadataGroup, boolean)`

All of them should prevent the deletion of the meta-data, preson, or meta-data group object in the case the quantity is set to `1m` or `+`. The behaviour can be overriden by setting the boolean parameter `force` to `true`. However, the syntax of the `if` checks misses the required negation, turning the function to behave just the opposite (only checking for `1m` or `+` in case `force` is `true`). I wondered why nobody ever noticed, and found out that the function is always only called from another delegate function,

* `removeMetadata(Metadata)`
* `removePerson(Person)`
* `removeMetadataGroup(MetadataGroup)`

with `force` set to `false`. Thus the checks **never** apply. Code can be refactored to

* incorporate the code part not circumvented by the always-`false` parameter into the one-parameter _remove_ functions
* remove the two-parameter _remove_ functions

**Comment by henning-gerhardt** [comment]
As long as  return value of this methods are not evaluated / used (at least in Kitodo.Production), this methods could be simplified.
