### ISSUE TITLE
Broken backward compatibility with old XStream files

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-ugh#55]
Removal of dead code (class fields) in #50 broke reading of XStream files created with earlier versions of Ugh. The reason is that package and class names, field names and field types used in the Java code implicitly declare the DTD of the XStream file format. Thus, any changes here break importability of existing XStream files. The clean-up needs to be undone.

**Comment by henning-gerhardt** [comment]
Someone is still using this format? I'm impressed!
