### ISSUE TITLE
Meta-data groups are duplicated on anchor file access

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-ugh#71]
Reason is that `newStruct.addMetadataGroup(mdnew);` is called twice in [DocStruct.java, ll. 748−751](https://github.com/kitodo/kitodo-ugh/blob/2.x/ugh/src/ugh/dl/DocStruct.java#L748-L751). Looks like a merge gone wrong. Fix is to delete lines 749−752.

**Comment by henning-gerhardt** [comment]
Looks like this issue was introduced by commit 20bd56082d1932b4956987584f76c92c6163a0d2 in 2013.

**Comment by henning-gerhardt** [comment]
Closing as pull request is merged.
