### ISSUE TITLE
Meta-data groups are duplicated during file read

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-ugh#79]
There is another instance of the bug described in #71 in [DocStruct.java, ll. 570−575](https://github.com/kitodo/kitodo-ugh/blob/2.x/ugh/src/ugh/dl/DocStruct.java#L570-L575). Fix is to delete lines 573−575.

**Comment by henning-gerhardt** [comment]
Closing as issue is resolved.
